#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_ZipCar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZipCar")]
	public partial class ZipCarDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCarro_has_Garagem(Carro_has_Garagem instance);
    partial void UpdateCarro_has_Garagem(Carro_has_Garagem instance);
    partial void DeleteCarro_has_Garagem(Carro_has_Garagem instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCliente_aluga_Carro(Cliente_aluga_Carro instance);
    partial void UpdateCliente_aluga_Carro(Cliente_aluga_Carro instance);
    partial void DeleteCliente_aluga_Carro(Cliente_aluga_Carro instance);
    partial void InsertGaragem(Garagem instance);
    partial void UpdateGaragem(Garagem instance);
    partial void DeleteGaragem(Garagem instance);
    partial void InsertCarro(Carro instance);
    partial void UpdateCarro(Carro instance);
    partial void DeleteCarro(Carro instance);
    #endregion
		
		public ZipCarDataContext() : 
				base(global::DAL_ZipCar.Properties.Settings.Default.ZipCarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ZipCarDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZipCarDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZipCarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZipCarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Carro_has_Garagem> Carro_has_Garagems
		{
			get
			{
				return this.GetTable<Carro_has_Garagem>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Cliente_aluga_Carro> Cliente_aluga_Carros
		{
			get
			{
				return this.GetTable<Cliente_aluga_Carro>();
			}
		}
		
		public System.Data.Linq.Table<Garagem> Garagems
		{
			get
			{
				return this.GetTable<Garagem>();
			}
		}
		
		public System.Data.Linq.Table<Carro> Carros
		{
			get
			{
				return this.GetTable<Carro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _idCliente;
		
		private int _tipo;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OntipoChanging(int value);
    partial void OntipoChanged();
    #endregion
		
		public Usuario()
		{
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int NOT NULL")]
		public int tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Usuario", Storage="_Cliente", ThisKey="idCliente", OtherKey="idCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._idCliente = value.idCliente;
					}
					else
					{
						this._idCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carro_has_Garagem")]
	public partial class Carro_has_Garagem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGaragem;
		
		private int _idCarro;
		
		private EntityRef<Garagem> _Garagem;
		
		private EntityRef<Carro> _Carro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGaragemChanging(int value);
    partial void OnidGaragemChanged();
    partial void OnidCarroChanging(int value);
    partial void OnidCarroChanged();
    #endregion
		
		public Carro_has_Garagem()
		{
			this._Garagem = default(EntityRef<Garagem>);
			this._Carro = default(EntityRef<Carro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGaragem", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idGaragem
		{
			get
			{
				return this._idGaragem;
			}
			set
			{
				if ((this._idGaragem != value))
				{
					if (this._Garagem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidGaragemChanging(value);
					this.SendPropertyChanging();
					this._idGaragem = value;
					this.SendPropertyChanged("idGaragem");
					this.OnidGaragemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCarro
		{
			get
			{
				return this._idCarro;
			}
			set
			{
				if ((this._idCarro != value))
				{
					if (this._Carro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarroChanging(value);
					this.SendPropertyChanging();
					this._idCarro = value;
					this.SendPropertyChanged("idCarro");
					this.OnidCarroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Garagem_Carro_has_Garagem", Storage="_Garagem", ThisKey="idGaragem", OtherKey="idGaragem", IsForeignKey=true)]
		public Garagem Garagem
		{
			get
			{
				return this._Garagem.Entity;
			}
			set
			{
				Garagem previousValue = this._Garagem.Entity;
				if (((previousValue != value) 
							|| (this._Garagem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Garagem.Entity = null;
						previousValue.Carro_has_Garagems.Remove(this);
					}
					this._Garagem.Entity = value;
					if ((value != null))
					{
						value.Carro_has_Garagems.Add(this);
						this._idGaragem = value.idGaragem;
					}
					else
					{
						this._idGaragem = default(int);
					}
					this.SendPropertyChanged("Garagem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carro_Carro_has_Garagem", Storage="_Carro", ThisKey="idCarro", OtherKey="idCarro", IsForeignKey=true)]
		public Carro Carro
		{
			get
			{
				return this._Carro.Entity;
			}
			set
			{
				Carro previousValue = this._Carro.Entity;
				if (((previousValue != value) 
							|| (this._Carro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carro.Entity = null;
						previousValue.Carro_has_Garagems.Remove(this);
					}
					this._Carro.Entity = value;
					if ((value != null))
					{
						value.Carro_has_Garagems.Add(this);
						this._idCarro = value.idCarro;
					}
					else
					{
						this._idCarro = default(int);
					}
					this.SendPropertyChanged("Carro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCategoria;
		
		private string _descricao;
		
		private EntitySet<Carro> _Carros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public Categoria()
		{
			this._Carros = new EntitySet<Carro>(new Action<Carro>(this.attach_Carros), new Action<Carro>(this.detach_Carros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Carro", Storage="_Carros", ThisKey="idCategoria", OtherKey="idCategoria")]
		public EntitySet<Carro> Carros
		{
			get
			{
				return this._Carros;
			}
			set
			{
				this._Carros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carros(Carro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_Carros(Carro entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private string _nome;
		
		private string _CPFCNPJ;
		
		private string _pesTip;
		
		private System.DateTime _datanasc;
		
		private string _carteiraNum;
		
		private System.DateTime _carteiraVal;
		
		private string _carteiraCat;
		
		private string _numCartao;
		
		private System.DateTime _cartaoVal;
		
		private string _telefoneRes;
		
		private string _telefoneCel;
		
		private string _status;
		
		private string _cidade;
		
		private string _uf;
		
		private string _logradouro;
		
		private int _numero;
		
		private string _complemento;
		
		private string _bairro;
		
		private string _cep;
		
		private string _sexo;
		
		private string _email;
		
		private EntitySet<Usuario> _Usuarios;
		
		private EntitySet<Cliente_aluga_Carro> _Cliente_aluga_Carros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnCPFCNPJChanging(string value);
    partial void OnCPFCNPJChanged();
    partial void OnpesTipChanging(string value);
    partial void OnpesTipChanged();
    partial void OndatanascChanging(System.DateTime value);
    partial void OndatanascChanged();
    partial void OncarteiraNumChanging(string value);
    partial void OncarteiraNumChanged();
    partial void OncarteiraValChanging(System.DateTime value);
    partial void OncarteiraValChanged();
    partial void OncarteiraCatChanging(string value);
    partial void OncarteiraCatChanged();
    partial void OnnumCartaoChanging(string value);
    partial void OnnumCartaoChanged();
    partial void OncartaoValChanging(System.DateTime value);
    partial void OncartaoValChanged();
    partial void OntelefoneResChanging(string value);
    partial void OntelefoneResChanged();
    partial void OntelefoneCelChanging(string value);
    partial void OntelefoneCelChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnufChanging(string value);
    partial void OnufChanged();
    partial void OnlogradouroChanging(string value);
    partial void OnlogradouroChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Cliente()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			this._Cliente_aluga_Carros = new EntitySet<Cliente_aluga_Carro>(new Action<Cliente_aluga_Carro>(this.attach_Cliente_aluga_Carros), new Action<Cliente_aluga_Carro>(this.detach_Cliente_aluga_Carros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCNPJ", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string CPFCNPJ
		{
			get
			{
				return this._CPFCNPJ;
			}
			set
			{
				if ((this._CPFCNPJ != value))
				{
					this.OnCPFCNPJChanging(value);
					this.SendPropertyChanging();
					this._CPFCNPJ = value;
					this.SendPropertyChanged("CPFCNPJ");
					this.OnCPFCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesTip", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string pesTip
		{
			get
			{
				return this._pesTip;
			}
			set
			{
				if ((this._pesTip != value))
				{
					this.OnpesTipChanging(value);
					this.SendPropertyChanging();
					this._pesTip = value;
					this.SendPropertyChanged("pesTip");
					this.OnpesTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datanasc", DbType="Date NOT NULL")]
		public System.DateTime datanasc
		{
			get
			{
				return this._datanasc;
			}
			set
			{
				if ((this._datanasc != value))
				{
					this.OndatanascChanging(value);
					this.SendPropertyChanging();
					this._datanasc = value;
					this.SendPropertyChanged("datanasc");
					this.OndatanascChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carteiraNum", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string carteiraNum
		{
			get
			{
				return this._carteiraNum;
			}
			set
			{
				if ((this._carteiraNum != value))
				{
					this.OncarteiraNumChanging(value);
					this.SendPropertyChanging();
					this._carteiraNum = value;
					this.SendPropertyChanged("carteiraNum");
					this.OncarteiraNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carteiraVal", DbType="Date NOT NULL")]
		public System.DateTime carteiraVal
		{
			get
			{
				return this._carteiraVal;
			}
			set
			{
				if ((this._carteiraVal != value))
				{
					this.OncarteiraValChanging(value);
					this.SendPropertyChanging();
					this._carteiraVal = value;
					this.SendPropertyChanged("carteiraVal");
					this.OncarteiraValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carteiraCat", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string carteiraCat
		{
			get
			{
				return this._carteiraCat;
			}
			set
			{
				if ((this._carteiraCat != value))
				{
					this.OncarteiraCatChanging(value);
					this.SendPropertyChanging();
					this._carteiraCat = value;
					this.SendPropertyChanged("carteiraCat");
					this.OncarteiraCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCartao", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string numCartao
		{
			get
			{
				return this._numCartao;
			}
			set
			{
				if ((this._numCartao != value))
				{
					this.OnnumCartaoChanging(value);
					this.SendPropertyChanging();
					this._numCartao = value;
					this.SendPropertyChanged("numCartao");
					this.OnnumCartaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartaoVal", DbType="Date NOT NULL")]
		public System.DateTime cartaoVal
		{
			get
			{
				return this._cartaoVal;
			}
			set
			{
				if ((this._cartaoVal != value))
				{
					this.OncartaoValChanging(value);
					this.SendPropertyChanging();
					this._cartaoVal = value;
					this.SendPropertyChanged("cartaoVal");
					this.OncartaoValChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoneRes", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string telefoneRes
		{
			get
			{
				return this._telefoneRes;
			}
			set
			{
				if ((this._telefoneRes != value))
				{
					this.OntelefoneResChanging(value);
					this.SendPropertyChanging();
					this._telefoneRes = value;
					this.SendPropertyChanged("telefoneRes");
					this.OntelefoneResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoneCel", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string telefoneCel
		{
			get
			{
				return this._telefoneCel;
			}
			set
			{
				if ((this._telefoneCel != value))
				{
					this.OntelefoneCelChanging(value);
					this.SendPropertyChanging();
					this._telefoneCel = value;
					this.SendPropertyChanged("telefoneCel");
					this.OntelefoneCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string uf
		{
			get
			{
				return this._uf;
			}
			set
			{
				if ((this._uf != value))
				{
					this.OnufChanging(value);
					this.SendPropertyChanging();
					this._uf = value;
					this.SendPropertyChanged("uf");
					this.OnufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logradouro", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				if ((this._logradouro != value))
				{
					this.OnlogradouroChanging(value);
					this.SendPropertyChanging();
					this._logradouro = value;
					this.SendPropertyChanged("logradouro");
					this.OnlogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL")]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="VarChar(100)")]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Usuario", Storage="_Usuarios", ThisKey="idCliente", OtherKey="idCliente")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cliente_aluga_Carro", Storage="_Cliente_aluga_Carros", ThisKey="idCliente", OtherKey="idCliente")]
		public EntitySet<Cliente_aluga_Carro> Cliente_aluga_Carros
		{
			get
			{
				return this._Cliente_aluga_Carros;
			}
			set
			{
				this._Cliente_aluga_Carros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Cliente_aluga_Carros(Cliente_aluga_Carro entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Cliente_aluga_Carros(Cliente_aluga_Carro entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente_aluga_Carro")]
	public partial class Cliente_aluga_Carro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private int _idCarro;
		
		private System.DateTime _dataHoraRetirado;
		
		private System.Nullable<System.DateTime> _dataHoraDevolvido;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Carro> _Carro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnidCarroChanging(int value);
    partial void OnidCarroChanged();
    partial void OndataHoraRetiradoChanging(System.DateTime value);
    partial void OndataHoraRetiradoChanged();
    partial void OndataHoraDevolvidoChanging(System.Nullable<System.DateTime> value);
    partial void OndataHoraDevolvidoChanged();
    #endregion
		
		public Cliente_aluga_Carro()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Carro = default(EntityRef<Carro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCarro
		{
			get
			{
				return this._idCarro;
			}
			set
			{
				if ((this._idCarro != value))
				{
					if (this._Carro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCarroChanging(value);
					this.SendPropertyChanging();
					this._idCarro = value;
					this.SendPropertyChanged("idCarro");
					this.OnidCarroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataHoraRetirado", DbType="DateTime NOT NULL")]
		public System.DateTime dataHoraRetirado
		{
			get
			{
				return this._dataHoraRetirado;
			}
			set
			{
				if ((this._dataHoraRetirado != value))
				{
					this.OndataHoraRetiradoChanging(value);
					this.SendPropertyChanging();
					this._dataHoraRetirado = value;
					this.SendPropertyChanged("dataHoraRetirado");
					this.OndataHoraRetiradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataHoraDevolvido", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataHoraDevolvido
		{
			get
			{
				return this._dataHoraDevolvido;
			}
			set
			{
				if ((this._dataHoraDevolvido != value))
				{
					this.OndataHoraDevolvidoChanging(value);
					this.SendPropertyChanging();
					this._dataHoraDevolvido = value;
					this.SendPropertyChanged("dataHoraDevolvido");
					this.OndataHoraDevolvidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cliente_aluga_Carro", Storage="_Cliente", ThisKey="idCliente", OtherKey="idCliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Cliente_aluga_Carros.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Cliente_aluga_Carros.Add(this);
						this._idCliente = value.idCliente;
					}
					else
					{
						this._idCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carro_Cliente_aluga_Carro", Storage="_Carro", ThisKey="idCarro", OtherKey="idCarro", IsForeignKey=true)]
		public Carro Carro
		{
			get
			{
				return this._Carro.Entity;
			}
			set
			{
				Carro previousValue = this._Carro.Entity;
				if (((previousValue != value) 
							|| (this._Carro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carro.Entity = null;
						previousValue.Cliente_aluga_Carros.Remove(this);
					}
					this._Carro.Entity = value;
					if ((value != null))
					{
						value.Cliente_aluga_Carros.Add(this);
						this._idCarro = value.idCarro;
					}
					else
					{
						this._idCarro = default(int);
					}
					this.SendPropertyChanged("Carro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Garagem")]
	public partial class Garagem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idGaragem;
		
		private string _nome;
		
		private string _UF;
		
		private string _cidade;
		
		private string _bairro;
		
		private string _cep;
		
		private string _logradouro;
		
		private int _num;
		
		private string _complemento;
		
		private System.Nullable<int> _capacidade;
		
		private string _latitude;
		
		private string _longitude;
		
		private EntitySet<Carro_has_Garagem> _Carro_has_Garagems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidGaragemChanging(int value);
    partial void OnidGaragemChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnlogradouroChanging(string value);
    partial void OnlogradouroChanged();
    partial void OnnumChanging(int value);
    partial void OnnumChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OncapacidadeChanging(System.Nullable<int> value);
    partial void OncapacidadeChanged();
    partial void OnlatitudeChanging(string value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    #endregion
		
		public Garagem()
		{
			this._Carro_has_Garagems = new EntitySet<Carro_has_Garagem>(new Action<Carro_has_Garagem>(this.attach_Carro_has_Garagems), new Action<Carro_has_Garagem>(this.detach_Carro_has_Garagems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGaragem", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idGaragem
		{
			get
			{
				return this._idGaragem;
			}
			set
			{
				if ((this._idGaragem != value))
				{
					this.OnidGaragemChanging(value);
					this.SendPropertyChanging();
					this._idGaragem = value;
					this.SendPropertyChanged("idGaragem");
					this.OnidGaragemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logradouro", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				if ((this._logradouro != value))
				{
					this.OnlogradouroChanging(value);
					this.SendPropertyChanging();
					this._logradouro = value;
					this.SendPropertyChanged("logradouro");
					this.OnlogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num", DbType="Int NOT NULL")]
		public int num
		{
			get
			{
				return this._num;
			}
			set
			{
				if ((this._num != value))
				{
					this.OnnumChanging(value);
					this.SendPropertyChanging();
					this._num = value;
					this.SendPropertyChanged("num");
					this.OnnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="VarChar(100)")]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidade", DbType="Int")]
		public System.Nullable<int> capacidade
		{
			get
			{
				return this._capacidade;
			}
			set
			{
				if ((this._capacidade != value))
				{
					this.OncapacidadeChanging(value);
					this.SendPropertyChanging();
					this._capacidade = value;
					this.SendPropertyChanged("capacidade");
					this.OncapacidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="VarChar(15)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="VarChar(15)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Garagem_Carro_has_Garagem", Storage="_Carro_has_Garagems", ThisKey="idGaragem", OtherKey="idGaragem")]
		public EntitySet<Carro_has_Garagem> Carro_has_Garagems
		{
			get
			{
				return this._Carro_has_Garagems;
			}
			set
			{
				this._Carro_has_Garagems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carro_has_Garagems(Carro_has_Garagem entity)
		{
			this.SendPropertyChanging();
			entity.Garagem = this;
		}
		
		private void detach_Carro_has_Garagems(Carro_has_Garagem entity)
		{
			this.SendPropertyChanging();
			entity.Garagem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carro")]
	public partial class Carro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCarro;
		
		private int _idCategoria;
		
		private string _marca;
		
		private string _modelo;
		
		private int _ano;
		
		private string _placa;
		
		private string _renavam;
		
		private string _cor;
		
		private string _ar;
		
		private string _direcao;
		
		private string @__4portas;
		
		private string _gps;
		
		private decimal _valorloc;
		
		private string _URLimagem;
		
		private EntitySet<Carro_has_Garagem> _Carro_has_Garagems;
		
		private EntitySet<Cliente_aluga_Carro> _Cliente_aluga_Carros;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCarroChanging(int value);
    partial void OnidCarroChanged();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OnmarcaChanging(string value);
    partial void OnmarcaChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnanoChanging(int value);
    partial void OnanoChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OnrenavamChanging(string value);
    partial void OnrenavamChanged();
    partial void OncorChanging(string value);
    partial void OncorChanged();
    partial void OnarChanging(string value);
    partial void OnarChanged();
    partial void OndirecaoChanging(string value);
    partial void OndirecaoChanged();
    partial void On_4portasChanging(string value);
    partial void On_4portasChanged();
    partial void OngpsChanging(string value);
    partial void OngpsChanged();
    partial void OnvalorlocChanging(decimal value);
    partial void OnvalorlocChanged();
    partial void OnURLimagemChanging(string value);
    partial void OnURLimagemChanged();
    #endregion
		
		public Carro()
		{
			this._Carro_has_Garagems = new EntitySet<Carro_has_Garagem>(new Action<Carro_has_Garagem>(this.attach_Carro_has_Garagems), new Action<Carro_has_Garagem>(this.detach_Carro_has_Garagems));
			this._Cliente_aluga_Carros = new EntitySet<Cliente_aluga_Carro>(new Action<Cliente_aluga_Carro>(this.attach_Cliente_aluga_Carros), new Action<Cliente_aluga_Carro>(this.detach_Cliente_aluga_Carros));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCarro
		{
			get
			{
				return this._idCarro;
			}
			set
			{
				if ((this._idCarro != value))
				{
					this.OnidCarroChanging(value);
					this.SendPropertyChanging();
					this._idCarro = value;
					this.SendPropertyChanged("idCarro");
					this.OnidCarroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string marca
		{
			get
			{
				return this._marca;
			}
			set
			{
				if ((this._marca != value))
				{
					this.OnmarcaChanging(value);
					this.SendPropertyChanging();
					this._marca = value;
					this.SendPropertyChanged("marca");
					this.OnmarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this.OnmodeloChanging(value);
					this.SendPropertyChanging();
					this._modelo = value;
					this.SendPropertyChanged("modelo");
					this.OnmodeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Int NOT NULL")]
		public int ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this.OnanoChanging(value);
					this.SendPropertyChanging();
					this._ano = value;
					this.SendPropertyChanged("ano");
					this.OnanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renavam", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string renavam
		{
			get
			{
				return this._renavam;
			}
			set
			{
				if ((this._renavam != value))
				{
					this.OnrenavamChanging(value);
					this.SendPropertyChanging();
					this._renavam = value;
					this.SendPropertyChanged("renavam");
					this.OnrenavamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cor", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cor
		{
			get
			{
				return this._cor;
			}
			set
			{
				if ((this._cor != value))
				{
					this.OncorChanging(value);
					this.SendPropertyChanging();
					this._cor = value;
					this.SendPropertyChanged("cor");
					this.OncorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ar", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ar
		{
			get
			{
				return this._ar;
			}
			set
			{
				if ((this._ar != value))
				{
					this.OnarChanging(value);
					this.SendPropertyChanging();
					this._ar = value;
					this.SendPropertyChanged("ar");
					this.OnarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direcao", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string direcao
		{
			get
			{
				return this._direcao;
			}
			set
			{
				if ((this._direcao != value))
				{
					this.OndirecaoChanging(value);
					this.SendPropertyChanging();
					this._direcao = value;
					this.SendPropertyChanged("direcao");
					this.OndirecaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[4portas]", Storage="__4portas", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string _4portas
		{
			get
			{
				return this.@__4portas;
			}
			set
			{
				if ((this.@__4portas != value))
				{
					this.On_4portasChanging(value);
					this.SendPropertyChanging();
					this.@__4portas = value;
					this.SendPropertyChanged("_4portas");
					this.On_4portasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string gps
		{
			get
			{
				return this._gps;
			}
			set
			{
				if ((this._gps != value))
				{
					this.OngpsChanging(value);
					this.SendPropertyChanging();
					this._gps = value;
					this.SendPropertyChanged("gps");
					this.OngpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorloc", DbType="Decimal(5,2) NOT NULL")]
		public decimal valorloc
		{
			get
			{
				return this._valorloc;
			}
			set
			{
				if ((this._valorloc != value))
				{
					this.OnvalorlocChanging(value);
					this.SendPropertyChanging();
					this._valorloc = value;
					this.SendPropertyChanged("valorloc");
					this.OnvalorlocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLimagem", DbType="VarChar(200)")]
		public string URLimagem
		{
			get
			{
				return this._URLimagem;
			}
			set
			{
				if ((this._URLimagem != value))
				{
					this.OnURLimagemChanging(value);
					this.SendPropertyChanging();
					this._URLimagem = value;
					this.SendPropertyChanged("URLimagem");
					this.OnURLimagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carro_Carro_has_Garagem", Storage="_Carro_has_Garagems", ThisKey="idCarro", OtherKey="idCarro")]
		public EntitySet<Carro_has_Garagem> Carro_has_Garagems
		{
			get
			{
				return this._Carro_has_Garagems;
			}
			set
			{
				this._Carro_has_Garagems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carro_Cliente_aluga_Carro", Storage="_Cliente_aluga_Carros", ThisKey="idCarro", OtherKey="idCarro")]
		public EntitySet<Cliente_aluga_Carro> Cliente_aluga_Carros
		{
			get
			{
				return this._Cliente_aluga_Carros;
			}
			set
			{
				this._Cliente_aluga_Carros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categoria_Carro", Storage="_Categoria", ThisKey="idCategoria", OtherKey="idCategoria", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.Carros.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.Carros.Add(this);
						this._idCategoria = value.idCategoria;
					}
					else
					{
						this._idCategoria = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Carro_has_Garagems(Carro_has_Garagem entity)
		{
			this.SendPropertyChanging();
			entity.Carro = this;
		}
		
		private void detach_Carro_has_Garagems(Carro_has_Garagem entity)
		{
			this.SendPropertyChanging();
			entity.Carro = null;
		}
		
		private void attach_Cliente_aluga_Carros(Cliente_aluga_Carro entity)
		{
			this.SendPropertyChanging();
			entity.Carro = this;
		}
		
		private void detach_Cliente_aluga_Carros(Cliente_aluga_Carro entity)
		{
			this.SendPropertyChanging();
			entity.Carro = null;
		}
	}
}
#pragma warning restore 1591
